--
-- PostgreSQL database dump
--

\restrict QTEgI6IF2CeLArXI5CAxWSqkYsfPnJVS3hjqM7CiTzcWDzZYHrTX2PKuXHCFikQ

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-05-09 21:47:02

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 32770)
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.category OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 32769)
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 32777)
-- Name: customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer (
    id bigint NOT NULL,
    phone_number character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    middle_name character varying(255),
    is_active boolean,
    active boolean,
    image_url character varying(255),
    email character varying(255),
    password character varying(255)
);


ALTER TABLE public.customer OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 32776)
-- Name: customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 32786)
-- Name: employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee (
    id bigint NOT NULL,
    role character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    middle_name character varying(255),
    image_url character varying(255),
    email character varying(255),
    password character varying(255),
    CONSTRAINT employee_role_check CHECK (((role)::text = ANY ((ARRAY['BARISTA'::character varying, 'WAITER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.employee OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 32785)
-- Name: employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 32796)
-- Name: ingredient; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ingredient (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.ingredient OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 32795)
-- Name: ingredient_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ingredient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ingredient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 32803)
-- Name: order_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_item (
    id bigint NOT NULL,
    price_at_purchase numeric(38,2),
    quantity integer,
    order_id bigint,
    product_id bigint
);


ALTER TABLE public.order_item OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 32802)
-- Name: order_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 32876)
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    status character varying(255),
    total_price numeric(38,2),
    customer_id bigint,
    employee_id bigint,
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['ACCEPTED'::character varying, 'IN_PROGRESS'::character varying, 'READY'::character varying])::text[])))
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 32875)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 32810)
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    id bigint NOT NULL,
    price numeric(38,2),
    category_id bigint NOT NULL,
    name character varying(255),
    tag_id bigint,
    image_url character varying(255)
);


ALTER TABLE public.product OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 32809)
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 32817)
-- Name: product_ingredients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_ingredients (
    product_id bigint NOT NULL,
    ingredients_id bigint NOT NULL
);


ALTER TABLE public.product_ingredients OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 32830)
-- Name: tag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tag (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.tag OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 32829)
-- Name: tag_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4974 (class 0 OID 32770)
-- Dependencies: 220
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.category (id, name) FROM stdin;
1	Кофе
3	Холодные напитки
4	Десерты
5	Завтраки
6	Горячие напитки
\.


--
-- TOC entry 4976 (class 0 OID 32777)
-- Dependencies: 222
-- Data for Name: customer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customer (id, phone_number, first_name, last_name, middle_name, is_active, active, image_url, email, password) FROM stdin;
9	+375297654321	Елена	Онипченко	Вячеславовна	\N	\N	/api/images/889942bb-41f5-4f4d-8f95-59a7b740c62c_photo_5463069697982011317_y.jpg	elenaonipchenco@gmail.com	elena1996
10	+375333280270	Екатерина	Огородник	Вячеславовна	\N	\N	/api/images/5ac88c6c-cb57-45b4-baca-3f3ba8280eab_photo_5463069697982011411_y.jpg	\N	\N
13	+375298976541	Арина	Савицкая	\N	\N	\N	\N	arinasavytskaya@gmail.com	arina1
7	+375333166637	Кирилл	Огородник	Вячеславович	\N	\N	/api/images/2f2c4a46-07a1-4fbb-b7bc-ba47920d5d17_photo_5454374875993674809_y.jpg	kirillogorodnik@gmail.com	kirill
4	+375292004885	Вячеслав	Онипченко	Валерьевич	\N	\N	/api/images/0a39e831-9d92-42b2-a049-3ff3cf938a28_photo_5454374875993674793_y.jpg	vyacheslavonipchenco@gmail.com	slava1
8	+375293184537	Мария	Добыш	Александровна	\N	\N	/api/images/7cfb79bd-68fc-45c2-966b-b5f80a484b65_photo_5454374875993674818_y.jpg	msh_dbsh@gmail.com	masha!
3	+375333280270	Ирина	Бойченко	Анатольевна	\N	\N		irinaboychenko@gmail.com	irina1
\.


--
-- TOC entry 4978 (class 0 OID 32786)
-- Dependencies: 224
-- Data for Name: employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee (id, role, first_name, last_name, middle_name, image_url, email, password) FROM stdin;
4	BARISTA	Алеся	Басюк	Владимировна	\N	\N	\N
5	BARISTA	Ника	Волкович	Ивановна	\N	\N	\N
3	WAITER	Дарья	Космицкая	Витальевна	/api/images/4cecdd42-3dc2-44c7-a41d-e1be4ce4f4c4_photo_5452123076179989417_y.jpg	\N	\N
6	ADMIN	Екатерина	Огородник	Вячеславовна	/api/images/aa50ea70-cbac-4769-85bf-4828ae966f75_photo_5463069697982011411_y.jpg	kateeogorodnik@gmail.com	admin!
\.


--
-- TOC entry 4980 (class 0 OID 32796)
-- Dependencies: 226
-- Data for Name: ingredient; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ingredient (id, name) FROM stdin;
1	Молоко
2	Сливки
3	Кофейные зёрна
4	Какао
5	Сахар
7	Яйца
6	Творог
8	Клубника
9	Киви
10	Мороженое
11	Какао парошок
12	Чай
13	Банан
14	Манная каша
15	Печенье
16	Мука
17	Сок
18	Сироп ванильный
19	Шоколад
20	Апельсин
\.


--
-- TOC entry 4982 (class 0 OID 32803)
-- Dependencies: 228
-- Data for Name: order_item; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_item (id, price_at_purchase, quantity, order_id, product_id) FROM stdin;
19	6.00	1	30	16
20	6.50	1	31	15
21	8.50	1	31	12
22	5.00	1	32	5
23	9.00	1	32	17
26	6.00	1	34	16
27	4.00	1	34	18
28	4.50	1	35	8
29	9.50	1	35	11
30	6.00	1	36	16
31	9.00	1	36	10
32	5.30	1	37	9
33	9.00	1	37	10
34	6.50	2	37	15
35	9.00	1	37	17
36	8.50	1	37	12
37	8.50	1	39	12
38	9.00	1	29	17
39	4.00	1	29	18
40	9.00	1	40	17
41	11.00	1	40	28
42	9.00	1	41	17
43	7.00	1	41	27
44	9.00	1	42	17
45	8.50	1	42	26
46	5.00	1	43	5
47	7.00	1	43	27
48	9.00	1	44	20
49	11.00	1	44	28
50	6.70	1	45	15
51	7.00	1	45	25
52	6.00	1	46	16
53	9.00	1	46	17
54	6.70	1	47	15
55	4.80	1	47	27
56	3.40	1	48	31
57	7.00	1	48	25
58	8.50	1	49	22
59	7.00	1	49	25
60	7.00	1	50	25
61	7.00	1	50	6
62	10.00	1	51	24
63	8.50	1	51	12
64	5.00	1	52	5
65	8.20	1	52	17
66	8.20	3	53	17
\.


--
-- TOC entry 4989 (class 0 OID 32876)
-- Dependencies: 235
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (id, status, total_price, customer_id, employee_id) FROM stdin;
30	READY	6.00	8	6
31	READY	15.00	7	3
32	READY	14.00	3	6
34	READY	10.00	3	5
35	READY	14.00	3	5
38	READY	0.00	4	3
39	READY	8.50	4	6
37	READY	44.80	4	3
36	READY	15.00	8	5
29	READY	13.00	8	5
41	ACCEPTED	16.00	8	4
40	READY	20.00	8	5
42	READY	17.50	8	6
43	ACCEPTED	12.00	8	6
46	ACCEPTED	15.00	9	6
44	READY	20.00	7	5
45	READY	13.70	7	5
47	READY	11.50	9	6
48	READY	10.40	10	6
49	ACCEPTED	15.50	10	3
50	ACCEPTED	14.00	10	3
51	ACCEPTED	18.50	10	3
52	ACCEPTED	13.20	10	6
53	ACCEPTED	24.60	10	6
\.


--
-- TOC entry 4984 (class 0 OID 32810)
-- Dependencies: 230
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product (id, price, category_id, name, tag_id, image_url) FROM stdin;
8	4.50	6	Чай чёрный	1	/api/images/3e6de66d-462d-4d23-af97-47cfb491309b_загружено (3).jfif
31	3.40	6	Чай зелёный	1	/api/images/e43cc5d2-3d47-43f4-a549-64b198b76c71_Green tea - Stylized Artistic.jfif
9	5.30	6	Какао	1	/api/images/0343c301-fd87-4644-beaa-ed1e61dd2e42_загружено (4).jfif
25	7.00	4	Вафли с мороженым	1	/api/images/3697183b-e7ba-4ac3-8153-154c071f6a26_waffle_no_plate.jpg
14	7.60	1	Айс-Латте	4	/api/images/2c1bc8b6-3d13-42e6-8a34-41c24414edda_ChatGPT Image 3 мая 2026 г., 19_51_18.png
15	6.70	1	Латте	1	/api/images/db5b70c9-532e-4424-a4ff-d81b0d4beb54_ChatGPT Image 2 мая 2026 г., 18_33_07.png
5	5.00	1	Американо	1	/api/images/26fa81d3-5135-40ae-9a3b-7719ec407ec7_ChatGPT Image 2 мая 2026 г., 18_28_37.png
30	6.20	3	Молочный коктейль шоколадный	1	/api/images/0cd57a57-7b13-461e-9078-6c4b332dbf9d_Download AI generated Chocolate milk shake png isolated on transparent background for free.jfif
24	10.00	3	Коктейль молочный с клубникой	1	/api/images/eb623957-4972-4acb-aaf0-c5b235f6c469_ChatGPT Image 3 мая 2026 г., 19_54_06.png
6	7.00	3	Смузи	1	/api/images/34bebcd4-8876-48c2-a71b-bde7a94cc048_ChatGPT Image 3 мая 2026 г., 19_55_42.png
26	8.50	5	Запеканка	1	/api/images/1852f00b-420a-4ed7-9db6-a81e563abefc_꒰   ✿˳     𝗣𝗡𝗚  ' 𝖲     ⊹˙    🌿.jfif
11	9.50	5	Глазунья	1	/api/images/de91d626-a9f9-485b-9951-9af5a0b19fa2_⬫ ׄ  ꪆ୧ ׅ 🧸.jfif
27	4.80	4	Эклер	1	/api/images/86e2c1de-b296-4d78-b003-13792a718652_загружено.jfif
21	9.00	1	Мокко	1	/api/images/a737d926-8c69-42af-be60-eebac3e5f03e_ChatGPT Image 2 мая 2026 г., 18_52_37.png
17	8.20	4	Павлова	1	/api/images/4f9b8449-1927-4f68-92b5-3dd2bd687010_ChatGPT Image 2 мая 2026 г., 19_15_21.png
10	9.00	5	Сырники	1	/api/images/7febc9bd-21dc-4839-a726-a7c1cea26394_ChatGPT Image 5 мая 2026 г., 19_36_58.png
23	6.70	1	Эспрессо	1	/api/images/cc061d29-3489-4eca-82a7-ad8362c11d9a_ChatGPT Image 2 мая 2026 г., 19_20_13.png
16	6.00	1	Капучино	1	/api/images/8f7aecba-ecc8-4351-b743-0304f947d114_ChatGPT Image 2 мая 2026 г., 19_21_34.png
20	9.00	1	Раф	1	/api/images/38fce1d7-847d-4b73-a9aa-1aed713f3d46_ChatGPT Image 2 мая 2026 г., 19_23_01.png
22	8.50	1	Флэт Уайт	1	/api/images/22321898-ac30-4c53-9da7-c25122801a84_ChatGPT Image 2 мая 2026 г., 19_24_34.png
28	8.20	4	Панкейки	1	/api/images/8f3d06bc-3b48-4289-b7f9-e8e7c4e361a8_Fresh pancakes stack with berries and syrup on transparent background.jfif
19	8.00	6	Горячий шоколад	1	/api/images/916c67f5-b48e-462b-bbde-95e29f969226_ChatGPT Image 5 мая 2026 г., 20_59_53.png
18	4.00	4	Шоколадный маффин	1	/api/images/1321cc9a-1629-4b55-a1e7-d80226bef7a0_загружено.jfif
12	8.50	4	Чизкейк	1	/api/images/b0a8f36c-ffd5-4b26-8812-cff6bc63a318_загружено (1).jfif
\.


--
-- TOC entry 4985 (class 0 OID 32817)
-- Dependencies: 231
-- Data for Name: product_ingredients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product_ingredients (product_id, ingredients_id) FROM stdin;
15	5
15	2
15	3
5	1
5	3
30	1
30	19
28	16
28	5
30	10
28	1
28	7
18	16
18	1
18	7
18	4
18	5
12	6
12	15
8	12
8	5
31	5
31	12
9	12
9	1
21	4
21	3
21	11
21	5
21	1
25	7
25	10
25	16
25	5
14	3
14	17
24	5
24	10
24	1
24	8
6	8
6	9
26	16
26	7
26	5
26	14
11	7
27	1
27	5
27	16
27	7
17	5
17	2
17	8
17	7
10	6
10	5
10	14
23	3
23	5
16	1
16	3
20	3
20	18
20	1
20	2
22	3
19	5
19	1
19	11
22	1
\.


--
-- TOC entry 4987 (class 0 OID 32830)
-- Dependencies: 233
-- Data for Name: tag; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tag (id, name) FROM stdin;
1	Стандарт
4	Весна
\.


--
-- TOC entry 4995 (class 0 OID 0)
-- Dependencies: 219
-- Name: category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.category_id_seq', 6, true);


--
-- TOC entry 4996 (class 0 OID 0)
-- Dependencies: 221
-- Name: customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customer_id_seq', 13, true);


--
-- TOC entry 4997 (class 0 OID 0)
-- Dependencies: 223
-- Name: employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_id_seq', 6, true);


--
-- TOC entry 4998 (class 0 OID 0)
-- Dependencies: 225
-- Name: ingredient_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ingredient_id_seq', 20, true);


--
-- TOC entry 4999 (class 0 OID 0)
-- Dependencies: 227
-- Name: order_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_item_id_seq', 66, true);


--
-- TOC entry 5000 (class 0 OID 0)
-- Dependencies: 234
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 53, true);


--
-- TOC entry 5001 (class 0 OID 0)
-- Dependencies: 229
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_id_seq', 31, true);


--
-- TOC entry 5002 (class 0 OID 0)
-- Dependencies: 232
-- Name: tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tag_id_seq', 5, true);


--
-- TOC entry 4797 (class 2606 OID 32775)
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- TOC entry 4799 (class 2606 OID 32784)
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);


--
-- TOC entry 4803 (class 2606 OID 32794)
-- Name: employee employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pkey PRIMARY KEY (id);


--
-- TOC entry 4807 (class 2606 OID 32801)
-- Name: ingredient ingredient_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ingredient
    ADD CONSTRAINT ingredient_pkey PRIMARY KEY (id);


--
-- TOC entry 4809 (class 2606 OID 32808)
-- Name: order_item order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_pkey PRIMARY KEY (id);


--
-- TOC entry 4817 (class 2606 OID 32882)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 4813 (class 2606 OID 32823)
-- Name: product_ingredients product_ingredients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_ingredients
    ADD CONSTRAINT product_ingredients_pkey PRIMARY KEY (product_id, ingredients_id);


--
-- TOC entry 4811 (class 2606 OID 32816)
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- TOC entry 4815 (class 2606 OID 32835)
-- Name: tag tag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_pkey PRIMARY KEY (id);


--
-- TOC entry 4801 (class 2606 OID 32901)
-- Name: customer ukdwk6cx0afu8bs9o4t536v1j5v; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT ukdwk6cx0afu8bs9o4t536v1j5v UNIQUE (email);


--
-- TOC entry 4805 (class 2606 OID 32903)
-- Name: employee ukfopic1oh5oln2khj8eat6ino0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT ukfopic1oh5oln2khj8eat6ino0 UNIQUE (email);


--
-- TOC entry 4820 (class 2606 OID 32841)
-- Name: product fk1mtsbur82frn64de7balymq9s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fk1mtsbur82frn64de7balymq9s FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- TOC entry 4818 (class 2606 OID 32836)
-- Name: order_item fk551losx9j75ss5d6bfsqvijna; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT fk551losx9j75ss5d6bfsqvijna FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- TOC entry 4824 (class 2606 OID 32888)
-- Name: orders fk624gtjin3po807j3vix093tlf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk624gtjin3po807j3vix093tlf FOREIGN KEY (customer_id) REFERENCES public.customer(id);


--
-- TOC entry 4822 (class 2606 OID 32851)
-- Name: product_ingredients fkcjxxp1v84pkvofdwi58x85431; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_ingredients
    ADD CONSTRAINT fkcjxxp1v84pkvofdwi58x85431 FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- TOC entry 4825 (class 2606 OID 32893)
-- Name: orders fkog5v9ga2g2ukytypn4ocip6b4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkog5v9ga2g2ukytypn4ocip6b4 FOREIGN KEY (employee_id) REFERENCES public.employee(id);


--
-- TOC entry 4823 (class 2606 OID 32846)
-- Name: product_ingredients fkq51ay36hx4j4y345v8bkr2dix; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_ingredients
    ADD CONSTRAINT fkq51ay36hx4j4y345v8bkr2dix FOREIGN KEY (ingredients_id) REFERENCES public.ingredient(id);


--
-- TOC entry 4821 (class 2606 OID 32870)
-- Name: product fkskejd8b65v9fd1d68tdsob9ck; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fkskejd8b65v9fd1d68tdsob9ck FOREIGN KEY (tag_id) REFERENCES public.tag(id);


--
-- TOC entry 4819 (class 2606 OID 32883)
-- Name: order_item fkt4dc2r9nbvbujrljv3e23iibt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT fkt4dc2r9nbvbujrljv3e23iibt FOREIGN KEY (order_id) REFERENCES public.orders(id);


-- Completed on 2026-05-09 21:47:02

--
-- PostgreSQL database dump complete
--

\unrestrict QTEgI6IF2CeLArXI5CAxWSqkYsfPnJVS3hjqM7CiTzcWDzZYHrTX2PKuXHCFikQ

