spring:
  application:
    name: cafe-system

  datasource:
    url: jdbc:postgresql://localhost:5432/CafeDB
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  logging:
    level:
      root: INFO
      com:
        cafe:
          cafeapp: DEBUG

upload:
  path: uploads